In [15]:
import numpy as np
a=np.array([3,5,8,0,2,5])
print(a)
print(np.amax(a))
print(np.amin(a))
print(np.median(a))
print(np.mean(a))

[3 5 8 0 2 5]
8
0
4.0
3.8333333333333335


In [10]:
b=np.array([[1,2,3,4],[36,7,9,1],[1,4,7,3]])
print(np.amax(b))
print(np.ptp(b)) #returns range minimum to maximum
print(np.median(b))
print(np.median(b,axis=1))
print(np.median(b,axis=0))
print(b)

36
35
3.5
[2.5 8.  3.5]
[1. 4. 7. 3.]
[[ 1  2  3  4]
 [36  7  9  1]
 [ 1  4  7  3]]


In [19]:
c=np.array([[6,2,8,9,7],[2,7,1,9,3],[5,3,8,0,1]])
print(c)
print(np.median(c,axis=1)) #row is for axis=1 ....median works with sorting of array then give answer
print(np.median(c,axis=0)) #column for axis=0
print(np.mean(c,axis=1))
print(np.mean(c,axis=0))
#mean is sum of elements along axis divide by no.of elements whereas numpy average is the function that computes--
#--the weighted average according to their respective weight given in another array 

[[6 2 8 9 7]
 [2 7 1 9 3]
 [5 3 8 0 1]]
[7. 3. 3.]
[5. 3. 8. 9. 3.]
[6.4 4.4 3.4]
[4.33333333 4.         5.66666667 6.         3.66666667]


In [20]:
d=np.array([[[1,2],[3,4],[5,6]],[[1,3],[5,7],[9,11]]])
print(d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 1  3]
  [ 5  7]
  [ 9 11]]]


In [40]:
e=[1,2,3,4]
weight=[4,3,2,1]
avg=[x*y for x,y in zip(e,weight)]
avg2=sum(avg)/sum(e)
print(avg2)

f=np.product(e)   # to multiply whole array
print(f)


2.0
24


In [41]:
a=np.array([1,2,3,4])
wts=np.array([4,3,2,1])
print(np.average(a,weights=wts))
print(np.average([1,2,3,4],weights=[4,3,2,1],returned=True)) #first is average,second is sum of weights

2.0
(2.0, 10.0)


In [58]:
#sort,searching-----default:quick sort
x=np.array([4,2,7,9,8,2,1,5])
print(x)
print("sorting x:",np.sort(x))
y=np.array([[2,11,5],[9,6,3]])
print(y)
print("sorting y:",np.sort(y))   #default sort row-wise
print(np.sort(y,axis=0))
print(np.sort(y,axis=1))


[4 2 7 9 8 2 1 5]
sorting x: [1 2 2 4 5 7 8 9]
[[ 2 11  5]
 [ 9  6  3]]
sorting y: [[ 2  5 11]
 [ 3  6  9]]
[[ 2  6  3]
 [ 9 11  5]]
[[ 2  5 11]
 [ 3  6  9]]


In [68]:
dt=np.dtype([("name",'S10'),('age','int')])         #defining a data type in numpy
p=np.array([('shristi',25),('muskan',23),('sharad',22)],dtype=dt) 
print(dt)
print(p)
print(np.sort(p))   #default order sorting by name
print(np.sort(p,order='age'))  #sort by age
print(np.sort(p,order='name'))  #sort by name

[('name', 'S10'), ('age', '<i4')]
[(b'shristi', 25) (b'muskan', 23) (b'sharad', 22)]
[(b'muskan', 23) (b'sharad', 22) (b'shristi', 25)]
[(b'sharad', 22) (b'muskan', 23) (b'shristi', 25)]
[(b'muskan', 23) (b'sharad', 22) (b'shristi', 25)]


In [73]:
q=np.array([('shristi',25),('muskan',23),('sharad',22)],dtype=([("name",'S10'),('age','int')]))
print(q)


[(b'shristi', 25) (b'muskan', 23) (b'sharad', 22)]


In [78]:
t=np.array([3,2,8,9,4,6])
q=np.argsort(t)
print(q)  #it gives position of elements after sorting
r=np.array([[2,11,5],[9,6,3]])
print(r)
print("sorting r:",np.argsort(y))   
print(np.argsort(r,axis=0))
print(np.argsort(r,axis=1))
s=np.array(["karan","is","stupid","person","of","the","world"])
print(np.argsort(s))

[1 0 4 5 2 3]
[[ 2 11  5]
 [ 9  6  3]]
sorting r: [[0 2 1]
 [2 1 0]]
[[0 1 1]
 [1 0 0]]
[[0 2 1]
 [2 1 0]]
[1 0 4 3 2 5 6]


In [85]:
tp=('s','e','m','a','u','d')
st=('n','g','k','l','i','o')
k=np.lexsort((tp,st))
print(k)
print([tp[i]+" "+st[i] for i in k])
 # sort first tuple with refernce to sorting the second tuple

[1 4 2 3 0 5]
['e g', 'u i', 'm k', 'a l', 's n', 'd o']


In [87]:
tp=('muskan','lime','tackle','digit','self','father')
st=('2','4','1','6','11','4')
k=np.lexsort((tp,st))
print(k)
print([tp[i]+" "+st[i] for i in k])

[2 4 0 5 1 3]
['tackle 1', 'self 11', 'muskan 2', 'father 4', 'lime 4', 'digit 6']
