In [5]:
import numpy as np

# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

# Change False to True for each block of code to see what it does

# Accessing elements
if True:
    print (ridership[1, 3])
    print (ridership[1:3, 3:5])
    print (ridership[1, :])
    
# Vectorized operations on rows or columns
if True:
    print (ridership[0, :] + ridership[1, :])
    print (ridership[:, 0] + ridership[:, 1])
    
# Vectorized operations on entire arrays
if True:
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
    print (a + b)

def mean_riders_for_max_station(ridership):

    ans= ridership[0,:].argmax()
    
    print("station with maximum riders:",ans)
    l=[]
    for i in range(0,10):
        l.append(ridership[i,:].max())
        
        
    print("mean of maximum biker per day",max(l))    
    overall_mean = ridership.mean()
    mean_for_max = ridership[:,ans].mean()
    
    return (overall_mean, mean_for_max)
             
ans1,ans2=mean_riders_for_max_station(ridership)
print(ans1,"  ",ans2)             

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]
[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
station with maximum riders: 3
mean of maximum biker per day 6461
2342.6    3239.9


In [6]:
import numpy as np

# Change False to True for this block of code to see what it does

# NumPy axis argument
if True:
    a = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
    
    print (a.sum())
    print (a.sum(axis=0))
    print (a.sum(axis=1))
    
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

def min_and_max_riders_per_day(ridership):
    '''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. That is, find the maximum
    mean-ridership-per-day and the minimum mean-ridership-per-day for any
    subway station.
    '''
    mean_ridership=ridership.mean(axis=0)
    max_daily_ridership = mean_ridership.max()
    min_daily_ridership = mean_ridership.min()     # Replace this with your code
    
    return (max_daily_ridership, min_daily_ridership)

print(min_and_max_riders_per_day(ridership))

45
[12 15 18]
[ 6 15 24]
(3239.9, 1071.2)
