In [8]:
import numpy as np
a=np.arange(10)
b=np.array([1,4,7,8,0,3,2,3,5,5])
c=np.arange(10)
d=(int)(input("enter choice1-2"))
if(d==1):
    print(a-b)
elif(d==2):
    print(a-c)

enter choice1-21
[-1 -3 -5 -5  4  2  4  4  3  4]


In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.arange(5)
while(1):
    c=input("enter the choice(c,d,e,f,g) :")
    if(c=='c'):
        print(a+b)
    elif(c=='d'):
        print(a-b)
    elif(c=='e'):
        print(a*b)
    elif(c=='f'):
        print(np.sqrt(a))
    elif(c=='g'):
        print(np.exp(a))
    else:
        print("calculation over")
        break

enter the choice(c,d,e,f,g) :d
[1 1 1 1 1]
enter the choice(c,d,e,f,g) :f
[1.         1.41421356 1.73205081 2.         2.23606798]
enter the choice(c,d,e,f,g) :h
calculation over
